name: iOS starter workflow
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main 
        
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cocoapods
        run: |
          gem install cocoapods -v '1.11.2'
          pod install
        working-directory: ./SignIn

      - name: Fix Podfile Platform Assignment
        run: sed -i '' 's/platform :ios/platform :ios, "16.2"/' ./SignIn/Podfile

      - name: Fix Build Setting Overrides
        run: |
          sed -i '' 's/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES//' ./SignIn/Pods/Target\ Support\ Files/Pods-SignIn-SignInUITests/Pods-SignIn-SignInUITests.debug.xcconfig
          sed -i '' 's/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES//' ./SignIn/Pods/Target\ Support\ Files/Pods-SignIn-SignInUITests/Pods-SignIn-SignInUITests.release.xcconfig
      
      - name: Debug Workspace
        run: ls ./SignIn
   
      - name: Move Workspace
        run: mv ./SignIn.xcworkspace ./
        working-directory: ./SignIn
        
      - name: Build and Archive
        run: |
          xcodebuild clean archive -workspace SignIn.xcworkspace -scheme SignIn -sdk iphoneos -configuration Debug -archivePath $PWD/build/SignIn.xcarchive | xcpretty
        working-directory: ./
        
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/SignIn.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build
        working-directory: ./
