name: iOS starter workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Copy Podfile
        run: cp -r SignIn/Podfile .
        
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup

      - name: Install dependencies
        run: pod install --project-directory=SignIn/
      
      - name: Check current directory
        run: |
          pwd
          ls -al
      
      - name: Clean derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Build project
        run: |
          xcodebuild -workspace SignIn/SignIn.xcodeproj/project.pbxproj -scheme SignIn clean archive -configuration release -sdk iphoneos -archivePath SignIn.xcarchive
