name: iOS starter workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update
          cd SignIn
          pod install
          cd ..

      - name: Build and Archive
        run: xcodebuild archive -workspace SignIn/SignIn.xcworkspace -scheme SignIn -archivePath ${{ runner.workspace }}/_temp/SignIn.xcarchive

  export:
    name: Export IPA and Transfer to Remote Server
    needs: build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate ExportOptions.plist
        run: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
            <key>method</key>
            <string>development</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.newProject.SignIn</key>
              <string>DemoTest</string>
            </dict>
            <key>signingCertificate</key>
            <string>Apple Development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string>X372X3URRM</string>
            <key>thinning</key>
            <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath ${{ runner.workspace }}/_temp/SignIn.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ${{ runner.workspace }}/_temp/build

      - name: Create IPA Output Directory
        run: mkdir -p IPAOutput

      - name: Copy IPA to Output Directory
        run: cp -R ${{ runner.workspace }}/_temp/build/SignIn.ipa IPAOutput/SignIn.ipa

      - name: Display Success Message
        run: echo "IPA exported successfully"

      - name: Transfer IPA to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          key: ${{ secrets.REMOTE_SERVER_PRIVATE_KEY }}
          source: IPAOutput/SignIn.ipa
          target: /home/ubuntu/iOS/SignIn.ipa

