name: iOS starter workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clear CocoaPods cache
        run: pod cache clean --all
        working-directory: ./SignIn

      - name: Remove problematic pod
        run: |
          pod deintegrate
          rm Podfile.lock
        working-directory: ./SignIn

      - name: Reinstall CocoaPods
        run: pod install
        working-directory: ./SignIn

      - name: Fix Podfile Platform Assignment
        run: sed -i '' 's/platform :ios/platform :ios, "16.2"/' ./SignIn/Podfile

      - name: Debug Workspace
        run: ls ./SignIn

      - name: Build and Archive
        run: |
          xcodebuild clean archive -workspace SignIn/SignIn.xcworkspace -scheme SignIn -sdk iphoneos -configuration Debug -archivePath $PWD/build/SignIn.xcarchive | xcpretty
       
