name: iOS starter workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cocoapods
        run: gem install cocoapods -v '1.11.2'
        working-directory: ./SignIn

      - name: Clear CocoaPods cache
        run: pod cache clean --all
        working-directory: ./SignIn

      - name: Reinstall CocoaPods
        run: pod install
        working-directory: ./SignIn

      - name: Fix Podfile Platform Assignment
        run: sed -i '' 's/platform :ios/platform :ios, "16.2"/' ./SignIn/Podfile

      - name: Fix Build Setting Overrides
        run: |
          sed -i '' 's/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES//' ./SignIn/Pods/Target\ Support\ Files/Pods-SignIn-SignInUITests/Pods-SignIn-SignInUITests.debug.xcconfig
          sed -i '' 's/ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES//' ./SignIn/Pods/Target\ Support\ Files/Pods-SignIn-SignInUITests/Pods-SignIn-SignInUITests.release.xcconfig

      - name: Set up provisioning profile
        run: echo "$PROVISIONING_PROFILE" > ./SignIn/ProvisioningProfile.mobileprovision
        env:
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}

      - name: Set up code signing settings
        run: |
          echo "$CODE_SIGN_IDENTITY" > ./SignIn/CodeSigningIdentity
          echo "$PROVISIONING_PROFILE_SPECIFIER" > ./SignIn/ProvisioningProfileSpecifier
        env:
          CODE_SIGN_IDENTITY: ${{ secrets.CODE_SIGN_IDENTITY }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
      
      - name: Build and Archive
        id: build_archive
        run: |
          xcodebuild archive -workspace SignIn/SignIn.xcworkspace \
          -scheme SignIn -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
          -sdk iphonesimulator -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=16.2' \
          clean archive DEVELOPMENT_TEAM="X372X3URRM" \
          PROVISIONING_PROFILE_SPECIFIER="DemoTest" -allowProvisioningUpdates \
          | tee build_output.txt

      - name: Extract CODE_SIGN_IDENTITY
        id: extract_code_sign_identity
        run: |
          CODE_SIGN_IDENTITY=$(grep -Eo 'CODE_SIGN_IDENTITY = .+' build_output.txt | awk -F '= ' '{print $2}')
          echo "::set-output name=value::$CODE_SIGN_IDENTITY"

      - name: Export IPA
        if: ${{ success() && steps.build_archive.outcome == 'success' }}
        run: |
          xcodebuild -exportArchive -archivePath "$RUNNER_TEMP/SignIn.xcarchive" \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath "$RUNNER_TEMP/IPA" \
          CODE_SIGN_IDENTITY="${{ steps.extract_code_sign_identity.outputs.value }}"

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: SignIn-IPA
          path: ${{ runner.temp }}/IPA

